In [2]:
import numpy as np

In [4]:
# set seed
np.random.seed(123)

In [6]:
# set random state which is independent from the global seed
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

<h4>generate a random sample from interval [0,1) in given shape</h4>

In [10]:
# generate a random scalar
print(np.random.rand())
print(np.random.rand())

0.5513147690828912
0.7194689697855631


In [12]:
# random 1-D array
print(np.random.rand(3))

[0.4809319  0.39211752 0.34317802]


In [14]:
# 2-D
print(np.random.rand(2,4))


[[0.53182759 0.63440096 0.84943179 0.72445532]
 [0.61102351 0.72244338 0.32295891 0.36178866]]


In [16]:
# hien thi phan phoi chuan 
print(np.random.randn(3,3))

[[-1.77413406  2.36160126  0.03499308]
 [-0.34464169 -0.72503229  1.03960617]
 [-0.24172804 -0.11290536 -1.66069578]]


In [19]:
# np.random.randint(low,high,size,dtype)
print(np.random.randint(2,20,5,"i8"))

[ 5  5 13  9 11]


In [21]:
# float
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))
# same as np.random.rand()

[0.02942373 0.55204372 0.2402475  0.88480501 0.46023842 0.19317033
 0.2936925  0.81792751 0.55948738 0.67792545]
[0.80912668 0.86857215 0.41799246 0.05893816 0.478459   0.52115943
 0.58063202 0.309199   0.91988263 0.6553475 ]
[0.34924138 0.54109404 0.4490534  0.28232096 0.29587653 0.56348098
 0.71519128 0.51761868 0.35204183 0.63277886]
[0.87311902 0.16788844 0.98747832 0.34941493 0.82620513 0.06546154
 0.00535329 0.88694465 0.91131813 0.19940777]


In [31]:
# # np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10 ,replace = True, p =[0.1,0.8,0.1]))
# chua hieu p = weights ?

[1 1 0 1 1 1 1 1 1 1]


In [34]:
print(np.random.choice(3,10))

[2 0 2 1 1 2 2 0 1 0]


In [36]:
print(np.random.choice([1,0,6],10))

[0 1 6 6 6 6 6 1 6 0]


In [39]:
# shuffle array
a = np.array(range(10))
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
np.random.shuffle(a)
print(a)

[5 2 6 3 0 4 1 7 9 8]


In [47]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
b = np.array(range(10))
c = np.random.permutation((b))
print(b)
print(f"day la copy xong shuffle cua b {c}" )

[0 1 2 3 4 5 6 7 8 9]
day la copy xong shuffle cua b [9 2 1 6 3 7 4 0 8 5]
