<a href="https://colab.research.google.com/github/mongvuot336699/BT-matrix/blob/master/8_Combine_%26_Split_an_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a1 = np.array([[1,2,3,4],[1,2,3,4]])
a2 = np.array([[5,6,7,8],[5,6,7,8]])

In [8]:
# np.concatenate((a,b),axis = 0)
cat = np.concatenate((a1,a2),axis = 0)
cat2 = np.concatenate((a1,a2),axis = 1)
print(cat)
print(cat2)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [10]:
# np.vstack((a,b)) = np.r_[a,b]
cat = np.vstack((a1,a2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [12]:
# np.hstack((a,b)) = np.c_[a,b]
cat = np.hstack((a1,a2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [16]:
a3 = np.arange(0,36).reshape(6,6)
print(a3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [24]:
# split the array vertically into n evenly spaced chunks 
arr1 = np.vsplit(a3,2)
print(arr1)
arr1 = np.hsplit(a3,2)
print(arr1)
# chia ma tran thanh cac phan theo tham so thu 2 (a3,...)

[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])]
[array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [24, 25, 26],
       [30, 31, 32]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])]
