In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [10]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
    arr = np.array([[1,2,3],[4,5,6]],dtype='i2')
print(arr)
print('Data Type:' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data Type:int16


In [16]:
arr = np.arange(0,30,3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27]


np.linspace(start,stop,num_of_elements,endpoint=True, retstep = False)
<ul>
    <li>start</li>
    <li>stop</li>
    <li>num_of_elements</li>
    <li>endpoint</li>
    <li>retstep</li>
</ul>

In [19]:
arr, step_size = np.linspace(0,9,8,endpoint = False,retstep = True)
print(arr)
print("the step size is "+ str(step_size))

[0.    1.125 2.25  3.375 4.5   5.625 6.75  7.875]
the step size is 1.125


In [21]:
arr = np.random.rand(3,3)
print(arr)

[[0.35638339 0.3207441  0.24595045]
 [0.51840786 0.36640746 0.77547308]
 [0.72383213 0.84441569 0.31002395]]


In [25]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
arr = np.array([[1,2],[3,4],[5,6]],dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)
print("data type:" + str(zeros.dtype))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
data type:complex64


In [30]:
# same zeros is ones
arr = [[1,2,3],[4,5,6]]
ones = np.ones_like(arr)
print(ones)
print("data type :" + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
data type :int32


In [33]:
empty = np.empty((4,4))
print(empty)

[[4.67296746e-307 1.69121096e-306 1.86921822e-306 1.11256817e-306]
 [1.06811422e-306 1.42417221e-306 1.11260619e-306 8.90094053e-307]
 [1.86919378e-306 1.06809792e-306 1.37962456e-306 1.69111861e-306]
 [1.78020169e-306 1.37961777e-306 7.56599807e-307 5.33590898e-322]]


In [35]:
arr = np.array([[1,2,3],[4,5,7]],dtype = np.int64)
empty = np.empty_like(arr)
print(empty)
print("data typy :" + str(empty.dtype))

[[1 2 3]
 [4 5 7]]
data typy :int64


In [37]:
arr = np.full((4,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [39]:
arr = np.array([[1,2,3],[4,5,6]],dtype = np.float64)
full = np.full_like(arr,7)
print(full)
print("data type: " + str(full.dtype))

[[7. 7. 7.]
 [7. 7. 7.]]
data type: float64


In [40]:
arr = [[1,2,3],[5,6,7]]
print(np.repeat(arr,4))

[1 1 1 1 2 2 2 2 3 3 3 3 5 5 5 5 6 6 6 6 7 7 7 7]


In [47]:
arr = [[1,2,3],[4,5,6]]
print(np.repeat(arr,3,axis = 1)) # truc x = 1
print(np.repeat(arr,3,axis = 0)) # truc y = 0 

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [49]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [51]:
i_matrix = np.eye(5,k = -1)
print(i_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


<h4>Matrix diagonal <h4>
   

In [53]:
arr = np.random.rand(5,5)
print(arr)
print("Value on the diagonal   " + str(np.diag(arr))) # gia tri duong cheo

[[0.30989983 0.98768787 0.9888516  0.61589058 0.94164277]
 [0.69114208 0.08441626 0.96858753 0.69866574 0.10587861]
 [0.50369649 0.82542628 0.85410352 0.46214284 0.29942491]
 [0.2674878  0.02891189 0.77922328 0.39493976 0.93503465]
 [0.45933936 0.86010108 0.31694516 0.89596397 0.96536959]]
Value on the diagonal   [0.30989983 0.08441626 0.85410352 0.39493976 0.96536959]


In [54]:
arr = np.diag([1,2,3,4,5,6])
print(arr)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
